### ISSUE TITLE
demo_example_validation.m gives not consistent results with diffusion 

### ISSUE THREAD

**Issue by andreafarina** [fangq/mmc#100]
Dear @fangq,
I've run the example demo_example_validation.m and, after your last update, the results between diffusion and MMC are not in agreement anymore when using gpu. There is probably some normalization that has not been set after the GPU Photon sharing update. Good agreement if using `cfg.gpuid = -1.`
![image](https://github.com/user-attachments/assets/cbc8a0b7-1556-4a58-9c72-798c60c8d7a0).

Thanks a lot!

Best regards!

Andrea

**Comment by fangq** [comment]
@andreafarina, thanks for the report. I noticed that this is a regression caused by the recent implementation of the normalization for photon sharing (#99) on the GPU. now it is fixed.
