### ISSUE TITLE
Don't have ieee754.h in windows VS2013

### ISSUE THREAD

**Issue by CoBoGroup** [fangq/mmc#24]

**Comment by fangq** [comment]
please download the needed header files from this wiki page:

http://mcx.space/wiki/index.cgi?MMC/CompileLog/2016.1

the headers come from x86_64-w64-mingw32-gcc package installed via cygwin on windows.

**Comment by fangq** [comment]
if you just need to use mmc, you can simply download the precompiled packages in the release section, as well as the nightly built binary for windows. 

http://mcx.space/nightly/win64/

compiling mmc on windows require several components.

**Comment by CoBoGroup** [comment]
Thank you!
