### ISSUE TITLE
cfg.outputype = 'energy' yields strange results

### ISSUE THREAD

**Issue by zanklanecek** [fangq/mmc#39]
Setting cfg.outputtype = 'fluence' and converting it to absorbance via my own function yields results that are comparable with absorbance output from mcxyz.c. (Left graph on image - Absorbance). However, setting cfg.outputype = 'energy' gives me strange results, which are shown on right graph - Energy. 

Keeping in mind this fix #36 , the output of fluence was comparable (due to bug in code) with this absorbance that I calculated by myself. The 'energy' was still strange. 

What is your explanation for this? Is there something wrong in code or am I misinterpreting the output of 'energy'?

![image](https://user-images.githubusercontent.com/24533740/61258092-347a8380-a774-11e9-9974-c7734531fd51.png)

**Comment by fangq** [comment]
@zanklanecek, the 'energy' output records the accumulative energy in each element, in the unit of joule, not in joule/mm^3. you need to divide the energy output by the nodal or element volume (dependents on your basisorder setting). the nodal and element volumes can be calculated using nodevolume.m and elemvolume.m in iso2mesh, respectively.

**Comment by zanklanecek** [comment]
This is what I was thinking, but did not know how to calculate volumes of cells in barycentric dual mesh. Everything makes sense now. Thank you!
