### ISSUE TITLE
MMC crashes - Invalid PLC for 'disk' sourctype for small radius

### ISSUE THREAD

**Issue by zanklanecek** [fangq/mmc#41]
MMC (new and older builds) crashes wih error `Invalid PLC` for 'disk' source type when radius is smaller than 95% of mesh top surface dimensions.

For instance:
XY = 6 mm x 6 mm (distance from center to sides = 3mm)
beam_radius cant be lower than 2.8 mm 
If lower than 2.8 mm , MMC crashes with above mentioned error. 
```
cfg.srctype='disk';

cfg.srcpos=[0 0 1]; % 1 mm above top surface of mesh
cfg.srcdir=[0 0 -1];

cfg.srcparam1 = [beam_radius 0 0 0]; 
cfg.srcparam2 = [0 0 0];
```
For mesh that is shown in those 2 images:
epidermis - 0.07 mm
dermis - 3.43 mm
hair

![image](https://user-images.githubusercontent.com/24533740/61408334-15006980-a8e0-11e9-9dc9-e2ad46356c57.png)

![image](https://user-images.githubusercontent.com/24533740/61408341-1c277780-a8e0-11e9-82b7-ea637db488ed.png)

Is there a workaround or am I doing something wrong?

Edit: Same problem occurs if I place source in bottom where is only one surface.

**Comment by zanklanecek** [comment]
Update:

I am using Matlab 2019 so [this problem from MMC-users google group ](https://groups.google.com/forum/#!searchin/mmc-users/invalid$20plc|sort:date/mmc-users/QsTV8viWv9s/11WSkMcsJAAJ) is of different nature. 

It seems that I can change beam radius freely for meshes of cylindrical shape (image below). No error here.  

![image](https://user-images.githubusercontent.com/24533740/61417139-7af7eb80-a8f6-11e9-8942-2c6532a23628.png)

**Comment by fangq** [comment]
hi @zanklanecek, "`Invalid PLC`" is **not an mmc bug** - nor a bug at all. This is the most common issue that new iso2mesh/tetgen users has encountered. See iso2mesh FAQ#1

http://iso2mesh.sourceforge.net/cgi-bin/index.cgi?Doc/FAQ#I_am_getting_a_Two_subfaces_are_found_intersecting_each_other_error_what_should_I_do

`Invalid PLC` is issued by tetgen (http://tetgen.org) which iso2mesh uses as the backend of s2m/surf2mesh. If your surface mesh passed to s2m/surf2mesh containing self-intersecting elements, tetgen will refuse to mesh it. 

The surface that tetgen can handle has very specific requirements - such surface must be water-tight, and shall not contain any self-intersecting elements. 

You must create we well-posed surface in order for s2m/surf2mesh to tessellate. If your surface is a closed single-compartment surface, you may use meshcheckrepair(...,'meshfix') to fix the problems. You can also use the surface repairing menu in MeshLab to repair such defects, but generally speaking, surface repairing is very difficult.

I am going to close this issue, but please feel free to upload your meshing script so I can provide any additional suggestions.
