### ISSUE TITLE
MMC software

### ISSUE THREAD

**Issue by ArjunBangalore** [fangq/mmc#50]
Hi,
I am new to use of Mesh-based Monte Carlo (MMC) for MATLAB (MMC) software. I am trying to learn. I downloaded and installed the package along with iso2mesh package, added all the folders to Matlab path. When I run any demo, the software prints 'Unrecognized function or variable 'mm''. I searched for mmc.m and could not find it. Can you help me resolve this issue? I have attached
Message
the message.
Thanks,
Arjun
![image](https://user-images.githubusercontent.com/60360688/73203164-84b2a500-410a-11ea-9b25-5e8819cef7a2.png)

**Comment by fangq** [comment]
you see this error because mmc.mex* does not exist in the package you downloaded - you must have downloaded the source code package or a package that does not match your OS. please redownload and verify mmc.mex* exists under the unzipped folder.
