### ISSUE TITLE
GNU Octave 4.0 & onecube example don't work

### ISSUE THREAD

**Issue by ImmortalBuka** [fangq/mmc#7]
Onecube example
When I tried run plotmmcdebug.m in Octave, I receive "error: tetramesh: T must be an n-by-4 matrix"

**Comment by yaoruoyang** [comment]
So what's the dimension of your input T? If it's n-by-5, you can simply remove the last column because that's the media type, and the first 4 columns are the indices of nodes for each tetrahedron.

**Comment by fangq** [comment]
hi @ImmortalBuka, the issue is now fixed. it appears that the elem with the 5th column (tissue type) is not accepted by tetramesh. Please update your mmc to the latest git version, or apply the below simple patch

https://github.com/fangq/mmc/commit/1d01665aaac79df9cbbac7cfe5c8aefc7a52c338
