### ISSUE TITLE
meshreorient in mmc expects 3 outputs

### ISSUE THREAD

**Issue by Totrock** [fangq/mmc#70]
I have a problem with a basic simulation with mmc.
I am using Ubuntu 18.04 and GNU Octave, version 4.2.2.
I copied the example from the end of the output of "help mmclab" and tried to run it.

But I get this error:
```
generating tetrahedral mesh from closed surfaces ...
creating volumetric mesh from a surface mesh ...
volume mesh generation is complete
error: element number 3 undefined in return list
error: called from
    mmclab at line 288 column 30
    mmclab_help_example at line 19 column 5
```
line 288 is this one:
[cfg(i).elem, evol, idx]=meshreorient(cfg(i).node,cfg(i).elem(:,1:4));

on Ubuntu18.04 with Octave: (with the latest [iso2mesh](https://sourceforge.net/projects/iso2mesh/files/iso2mesh/1.9.6%20%28Lion%20Head%29/)  or the one from the [PPA](https://launchpad.net/~fangq/+archive/ubuntu/ppa))
> help meshreorient 
'meshreorient' is a function from the file /home/josef/iso2mesh196linux/meshreorient.m
 [newelem, evol]=meshreorient(node,elem)

On windows with matlab:
> help meshreorient
  [newelem, evol, idx]=meshreorient(node,elem)

Am I using some incompatible versions or is this a bug?

**Comment by fangq** [comment]
please check out the latest iso2mesh from github - the ppa version was old and does not have the 3rd output that is needed by mmclab

https://github.com/fangq/iso2mesh/blob/master/meshreorient.m

**Comment by Totrock** [comment]
This works. Thanks.
