### ISSUE TITLE
Incorrect normalized fluence output

### ISSUE THREAD

**Issue by Zhishen2022** [fangq/mmc#79]
Hi,

Recently, I occasionally found that the normalized fluence value will increase as the simulated photon number increases, which is against my understanding about the normalization operator. Please see bellow figures, the fluence on the same selected nodes on the surface of sphere mesh will increase as the simulated photon number increases from 10^7 to 10^9.
![image](https://user-images.githubusercontent.com/102486049/173431770-2d55694e-c43b-4327-9369-c1cc9c1e375d.png)
![image](https://user-images.githubusercontent.com/102486049/173431819-5fc4bf1d-5b83-496e-9ffe-8341fc5fba80.png)

I also attached bellow code for reproducing this problem. I will appreciate that if you could give some suggestions to fix it.
[Normalized_fluence_as_photon_number_revised.txt](https://github.com/fangq/mmc/files/8894020/Normalized_fluence_as_photon_number_revised.txt)

Actually, I tested the issue through MCXLAB, and it does not have such concern.

Thank you,
Zhishen

**Comment by ShijieYan** [comment]
Some observations from my end:
1. The difference becomes negligible if cfg.outputtype="energy", suggesting the ray-tracing and raw output quantities are properly handled.
2. It seems that the issue arises from the output normalization, specifically: https://github.com/fangq/mmc/blob/c3b15b238ac762b5ddefc8ae8beb686c97db3dfd/src/mmc_mesh.c#L1435-L1439
It is interesting that the discrepancies disappear if [this line](https://github.com/fangq/mmc/blob/c3b15b238ac762b5ddefc8ae8beb686c97db3dfd/src/mmc_mesh.c#L1438) becomes
`mesh->weight[(i * datalen + j)*cfg->srcnum + pair] *= mesh->nvol[j];`

**Comment by fangq** [comment]
@Zhishen2022, as @ShijieYan pointed out, this reported issue is related to the normalization issue in #82. 

I managed to find a fix to issue #82, and I retested your script, it appears the discrepancies are now gone.

here is the new test output
![image](https://github.com/fangq/mmc/assets/226913/48df2c99-21fa-4f7f-b8cc-b29fb49d7055)

feel free to test with the latest version, which you can download from http://mcx.space/nightly/github/

I am closing this ticket for now, but if you see any additional issue, feel free to reopen.

**Comment by Zhishen2022** [comment]
Hi Dr. Fang,

Thank you for your follow-up. It's great to hear that the normalization issue has been resolved.

I have a small question about the use of multiple sources of coherent illumination on the surface. We would like to shine multiple excitation sources on the tissue surface to excite fluorophores in vivo. These excitation sources originate from the same laser, which means that these multiple excitation sources will have the same phase, resulting in coherent illumination. Could I use MC to calculate the excitation light field within the tissue corresponding to this coherent illumination? If so, could you please share some suggestions, materials, or tools?

Thanks a lot!

Best regards
Zhishen

________________________________

**Comment by fangq** [comment]
@Zhishen2022, mcx, as well as most free MC tools, currently do not have capability to model coherence - although I would think that using the path-length information may be able to do something, but I haven't really look into this further. I know some studies used the pathlengths in MC to produce frequency-domain solutions, which also has phase information.

one special type of MC, called EMC, is supposed to be able to model coherence. I think my student @ShijieYan had wrote about a short comparison between EMC and other MC in this [polarized MCX paper.](https://doi.org/10.1117/1.JBO.27.8.083015)

please checkout this website and search relevant papers for more details

https://www.hunter.cuny.edu/physics/faculty/xu/electric-field-monte-carlo
