### ISSUE TITLE
Is there a way to get detp.p and detp.v of all exiting photons?

### ISSUE THREAD

**Issue by naitsok** [fangq/mmc#88]
Hello,
Thanks a lot for your simulation software!
I have a question about MMC.
Is there a way to get detp.p and detp.v of all the exiting photons similar to cfg.bc = '______111111' in MCX/MCXCL?
Thank you!

**Comment by fangq** [comment]
that's what [`cfg.savedetflag`](https://github.com/fangq/mcx/blob/v2024.2/mcxlab/mcxlab.m#L274-L283) is used for.
did you try setting `cfg.savedetflag='xv'`?

alternatively, you could also use [`cfg.saveexit`](https://github.com/fangq/mcx/blob/v2024.2/mcxlab/mcxlab.m#L285C11-L285C23)
